library(ggplot2)
library(ggthemes)
library(dplyr)
library(vroom)
library(forcats)
library(tidyr)
library(ggpubr)
#install.packages("tidytext")
library(tidytext)
library(tibble)
setwd("/hlamajority-paper/external/mhc_genotyping/")
source("scripts/functions/evaluate_predictions_functions.R")
# read in data
# CELL LINES
# NCI-60 RDS object generated by ./external/mhc_genotyping/scripts/evaluate_predictions_nci60.R 
results <- readRDS("../../data/processed/cell-lines-after-polysolver-change/majority/nci-full-results-hlamajority-majority-vote.Rds")
# NCI-60 full stats
df <- read.csv("../../data/processed/cell-lines-after-polysolver-change/majority/nci-full-stats-hlamajority-majority-vote.csv")

results$summary$Tool <- factor(
  results$summary$Tool,
  levels = c("kourami", "hlala", "polysolver", "optitype", "hlamajority"),
  labels = c("Kourami", "HLA*LA", "Polysolver", "Optitype", "nf-hlamajority")
)
df <- df %>% dplyr::mutate(Accuracy = 100*Accuracy)
df$Gene <- factor(df$Gene, levels = c("Overall", "A", "B", "C"))
df$Tool <- factor(
  df$Tool,
  levels = c("kourami", "hlala", "polysolver", "optitype", "hlamajority"),
  labels = c("Kourami", "HLA*LA", "Polysolver", "Optitype", "nf-hlamajority")
)

my_gene_labels <- c(
  "Overall" = "Overall Accuracy",
  "A"     = "HLA-A",
  "B"     = "HLA-B",
  "C"     = "HLA-C"
)

summarise_gene_tool <- function(results, gene, tool) {
  
  tool <- as.character(tool)
  
  x <- results$details[[gene]][[tool]]$error_types$Type
  
  tab <- table(x)
  
  data.frame(
    Gene  = gene,
    Tool  = tool,
    Type  = names(tab),
    Count = as.integer(tab),
    row.names = NULL
  )
}
tools <- unique(df$Tool)
tools_internal <- c("kourami", "hlala", "polysolver", "optitype", "hlamajority")

tools_labels <- c(
  kourami = "Kourami",
  hlala = "HLA*LA",
  polysolver = "Polysolver",
  optitype = "Optitype",
  hlamajority = "nf-hlamajority"
)

genes <- c("A", "B", "C")
final_df <- do.call(
  rbind,
  lapply(genes, function(g) {
    do.call(
      rbind,
      lapply(tools_internal, function(t) {
        summarise_gene_tool(results, g, t)
      })
    )
  })
) 

final_df_mismatches <- final_df |> 
  dplyr::filter(Type != "Correct") |>
  group_by(Gene, Tool) |>
  mutate(
    Percent = Count / sum(Count) * 100
  ) |>
  ungroup()

final_df_mismatches$Type <- factor(final_df_mismatches$Type,
                                   levels = c("Dropout (Hetero -> Homo)", "Hallucination (Homo -> Hetero)", "Partial Mismatch", "Complete Mismatch"),
                                   labels = c("Dropout", "Allele Gain", "Partial Mismatch", "Complete Mismatch")
)

final_df_mismatches$Tool <- factor(
  final_df_mismatches$Tool,
  levels = c("kourami", "hlala", "polysolver", "optitype", "hlamajority"),
  labels = c("Kourami", "HLA*LA", "Polysolver", "Optitype", "nf-hlamajority")
)


palette_mistake_types <- c(
  Correct = "#016FB9",
  Dropout = "#22AED1",
  "Allele Gain" = "#6D8EA0",
  "Partial Mismatch" = "#AFA98D",
  "Complete Mismatch" = "#182825"
)

p_types_percent_cell_lines <- ggplot(
  final_df_mismatches,
  aes(x = Type, y = Percent, fill = Type)
) +
  geom_col(
    width = 0.7,
    color = "black",
    linewidth = 0.2
  ) +
  facet_grid(
    Gene ~ Tool,
    scales = "fixed",
    labeller = labeller(Gene = my_gene_labels)
  ) +
  scale_y_continuous(
    expand = c(0, 0)
  ) +
  labs(
    x = "Outcome type",
    y = "Percent of errors",
    fill = "Type"
  ) +
  theme_bw() +
  theme(
    strip.background = element_rect(fill = "#f0f0f0"),
    strip.text = element_text(face = "bold", size = 18),
    panel.grid.major.x = element_blank(),
    # axis.text.x = element_text(
    #   angle = 45,
    #   hjust = 1,
    #   colour = "black"
    # ),
    axis.text.x = element_blank(),
    axis.text.y = element_text(colour = "black"),
    axis.title = element_text(size = 18),
    legend.position = "bottom",
    legend.title = element_text(size =18),
    legend.text = element_text(size = 16),
    plot.title = element_text(color="black", size=28, face="bold.italic"),
    panel.spacing = unit(0.8, "lines")
  ) +
  coord_cartesian(ylim = c(0, 100)) +
  scale_fill_manual(values = palette_mistake_types) +
  ggtitle("NCI-60 Cell lines error types (percent of total errors)")

p_types_percent_cell_lines

p_types_counts_cell_lines <- ggplot(
  final_df_mismatches,
  aes(x = Type, y = Count, fill = Type)
) +
  geom_col(
    width = 0.7,
    color = "black",
    linewidth = 0.2
  ) +
  facet_grid(
    Gene ~ Tool,
    scales = "fixed",
    labeller = labeller(Gene = my_gene_labels)
  ) +
  scale_y_continuous(
    limits = c(0, 10),
    breaks = seq(0, 10, by = 2),
    expand = c(0, 0)
  ) +
  labs(
    x = "Error type",
    y = "Number of errors",
    fill = "Type"
  ) +
  theme_bw() +
  theme(
    strip.background = element_rect(fill = "#f0f0f0"),
    strip.text = element_text(face = "bold", size = 18),
    panel.grid.major.x = element_blank(),
    # axis.text.x = element_text(
    #   angle = 45,
    #   hjust = 1,
    #   colour = "black"
    # ),
    axis.text.x = element_blank(),
    axis.text.y = element_text(colour = "black"),
    axis.title = element_text(size = 18),
    legend.position = "bottom",
    legend.title = element_text(size =18),
    legend.text = element_text(size = 16),
    panel.spacing.y = unit(1, "lines"),
    plot.title = element_text(color="black", size=28, face="bold.italic")
  ) +
  # coord_cartesian(ylim = c(0, 10)) +
  scale_fill_manual(values = palette_mistake_types) +
  ggtitle("NCI-60 Cell lines error types (number of errors)")

p_types_counts_cell_lines

# 1000 GENOMES
results_1000_genomes <- readRDS("../../data/processed/1000-genomes/majority/1000-genomes-full-results-hlamajority-majority-vote.Rds")
# 1000 GENOMES full stats
df_1000_genomes <- read.csv("../../data/processed/1000-genomes/majority/1000-genomes-full-stats-hlamajority-majority-vote.csv")

results_1000_genomes$summary$Tool <- factor(
  results_1000_genomes$summary$Tool,
  levels = c("kourami", "hlala", "polysolver", "optitype", "hlamajority"),
  labels = c("Kourami", "HLA*LA", "Polysolver", "Optitype", "nf-hlamajority")
)
df_1000_genomes <- df_1000_genomes %>% dplyr::mutate(Accuracy = 100*Accuracy)
df_1000_genomes$Gene <- factor(df_1000_genomes$Gene, levels = c("Overall", "A", "B", "C"))
df_1000_genomes$Tool <- factor(
  df_1000_genomes$Tool,
  levels = c("kourami", "hlala", "polysolver", "optitype", "hlamajority"),
  labels = c("Kourami", "HLA*LA", "Polysolver", "Optitype", "nf-hlamajority")
)

final_df_1000_genomes <- do.call(
  rbind,
  lapply(genes, function(g) {
    do.call(
      rbind,
      lapply(tools_internal, function(t) {
        summarise_gene_tool(results_1000_genomes, g, t)
      })
    )
  })
) 

final_df_mismatches_1000_genomes <- final_df_1000_genomes |> 
  dplyr::filter(Type != "Correct") |>
  group_by(Gene, Tool) |>
  mutate(
    Percent = Count / sum(Count) * 100
  ) |>
  ungroup()

final_df_mismatches_1000_genomes$Type <- factor(final_df_mismatches_1000_genomes$Type,
                                   levels = c("Dropout (Hetero -> Homo)", "Hallucination (Homo -> Hetero)", "Partial Mismatch", "Complete Mismatch"),
                                   labels = c("Dropout", "Allele Gain", "Partial Mismatch", "Complete Mismatch")
)

final_df_mismatches_1000_genomes$Tool <- factor(
  final_df_mismatches_1000_genomes$Tool,
  levels = c("kourami", "hlala", "polysolver", "optitype", "hlamajority"),
  labels = c("Kourami", "HLA*LA", "Polysolver", "Optitype", "nf-hlamajority")
)

p_types_percent_1000_genomes <- ggplot(
  final_df_mismatches_1000_genomes,
  aes(x = Type, y = Percent, fill = Type)
) +
  geom_col(
    width = 0.7,
    color = "black",
    linewidth = 0.2
  ) +
  facet_grid(
    Gene ~ Tool,
    scales = "fixed",
    labeller = labeller(Gene = my_gene_labels)
  ) +
  scale_y_continuous(
    expand = c(0, 0)
  ) +
  labs(
    x = "Outcome type",
    y = "Percent of errors",
    fill = "Type"
  ) +
  theme_bw() +
  theme(
    strip.background = element_rect(fill = "#f0f0f0"),
    strip.text = element_text(face = "bold", size = 18),
    panel.grid.major.x = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_text(colour = "black"),
    axis.title = element_text(size = 18),
    legend.position = "bottom",
    legend.title = element_text(size =18),
    legend.text = element_text(size = 16),
    plot.title = element_text(color="black", size=28, face="bold.italic"),
    panel.spacing = unit(0.8, "lines")
  ) +
  coord_cartesian(ylim = c(0, 100)) +
  scale_fill_manual(values = palette_mistake_types) +
  ggtitle("1000 Genomes error types (percent of total errors)")

p_types_percent_1000_genomes

p_types_counts_1000_genomes <- ggplot(
  final_df_mismatches_1000_genomes,
  aes(x = Type, y = Count, fill = Type)
) +
  geom_col(
    width = 0.7,
    color = "black",
    linewidth = 0.2
  ) +
  facet_grid(
    Gene ~ Tool,
    scales = "fixed",
    labeller = labeller(Gene = my_gene_labels)
  ) +
  scale_y_continuous(
    limits = c(0, 200),
    breaks = seq(0, 200, by = 40),
    expand = c(0, 0)
  ) +
  labs(
    x = "Error type",
    y = "Number of errors",
    fill = "Type"
  ) +
  theme_bw() +
  theme(
    strip.background = element_rect(fill = "#f0f0f0"),
    strip.text = element_text(face = "bold", size = 18),
    panel.grid.major.x = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_text(colour = "black"),
    axis.title = element_text(size = 18),
    legend.position = "bottom",
    legend.title = element_text(size =18),
    legend.text = element_text(size = 16),
    panel.spacing.y = unit(1, "lines"),
    plot.title = element_text(color="black", size=28, face="bold.italic")
  ) +
  # coord_cartesian(ylim = c(0, 10)) +
  scale_fill_manual(values = palette_mistake_types) +
  ggtitle("1000 Genomes error types (number of errors)")

p_types_counts_1000_genomes

combine.1000genomes.cell.lines.error.types.percent <- ggarrange(
  p_types_percent_1000_genomes, 
  p_types_percent_cell_lines,
  ncol = 1,
  labels = c("A", "B"),
  font.label=list(color="black",size=28, face = "bold")
)
combine.1000genomes.cell.lines.error.types.percent
ggsave(plot = combine.1000genomes.cell.lines.error.types.percent, filename = "/hlamajority-paper/results/thesis/plots/error-types-hlamajority-1000genomes-nci-combined-20260527.svg", width = 15, height = 20)
ggsave(plot = combine.1000genomes.cell.lines.error.types.percent, filename = "/hlamajority-paper/results/thesis/plots/error-types-hlamajority-1000genomes-nci-combined-20260525.pdf", width = 15, height = 20)
ggsave(plot = combine.1000genomes.cell.lines.error.types.percent, filename = "/hlamajority-paper/results/thesis/figures/error-types-hlamajority-1000genomes-nci-combined-20260525.pdf", width = 15, height = 20)

combine.1000genomes.cell.lines.error.types.counts <- ggarrange(
  p_types_counts_1000_genomes, 
  p_types_counts_cell_lines,
  ncol = 1,
  labels = c("A", "B"),
  font.label=list(color="black",size=28, face = "bold")
)

combine.1000genomes.cell.lines.error.types.counts
ggsave(plot = combine.1000genomes.cell.lines.error.types.counts, filename = "/hlamajority-paper/results/thesis/plots/counts-error-types-hlamajority-1000genomes-nci-combined-20260527.svg", width = 15, height = 20)
ggsave(plot = combine.1000genomes.cell.lines.error.types.counts, filename = "/hlamajority-paper/results/thesis/plots/counts-error-types-hlamajority-1000genomes-nci-combined-20260525.pdf", width = 15, height = 20)
ggsave(plot = combine.1000genomes.cell.lines.error.types.counts, filename = "/hlamajority-paper/results/thesis/figures/counts-error-types-hlamajority-1000genomes-nci-combined-20260525.pdf", width = 15, height = 20)
