library(ggplot2)
library(ggthemes)
library(dplyr)
library(vroom)
library(forcats)
library(tidyr)
library(ggpubr)
#install.packages("tidytext")
library(tidytext)
library(tibble)
setwd("/hlamajority-paper/external/mhc_genotyping/")
source("scripts/functions/evaluate_predictions_functions.R")
# read in data
# NCI-60 RDS object generated by ./external/mhc_genotyping/scripts/evaluate_predictions_nci60_lens.R 
results <- readRDS("../../data/processed/cell-lines-after-polysolver-change/lens-majority-benchmark/nci-full-results-lens-compare-hlamajority.Rds")
# NCI-60 full stats
df <- read.csv("../../data/processed/cell-lines-after-polysolver-change/lens-majority-benchmark/nci-full-stats-lens-compare-hlamajority.csv")

results$summary$Tool <- factor(
  results$summary$Tool,
  levels = c("kourami", "hlala", "polysolver", "optitype", "hlamajority", "arcasHLA", "HLAprofiler", "seq2HLA", "Optitype_ar", "Optitype_ad", "LENS-v1.8-consensus"),
  labels = c("Kourami", "HLA*LA", "Polysolver", "Optitype-DNA-hlamajority", "nf-hlamajority", "arcasHLA", "HLAprofiler", "seq2HLA", "Optitype-RNA", "Optitype-DNA-LENS", "LENS-v1.8-consensus")
)
df <- df %>% dplyr::filter(Tool != "Optitype_ad")
df <- df %>% dplyr::mutate(Accuracy = 100*Accuracy)
df$Gene <- factor(df$Gene, levels = c("Overall", "A", "B", "C"))
df$Tool <- factor(
  df$Tool,
  levels = c("kourami", "hlala", "polysolver", "optitype", "hlamajority", "arcasHLA", "HLAprofiler", "seq2HLA", "Optitype_ar", "LENS-v1.8-consensus"),
  labels = c("Kourami", "HLA*LA", "Polysolver", "Optitype-DNA", "nf-hlamajority", "arcasHLA", "HLAprofiler", "seq2HLA", "Optitype-RNA", "LENS-v1.8-consensus")
)

my_gene_labels <- c(
  "Overall" = "Overall Accuracy",
  "A"     = "HLA-A",
  "B"     = "HLA-B",
  "C"     = "HLA-C"
) 

# Figure: Accuracy per gene per tool

df.for.figure <- df %>%
  dplyr::select(Gene, Tool, Accuracy)
df.for.figure$Accuracy <- round(df.for.figure$Accuracy, 1)
df.for.figure <- df.for.figure %>%
  dplyr::mutate(
    Tool_ordered = reorder_within(Tool, Accuracy, Gene)
  )

tool_types <- c(
  "arcasHLA" = "RNA",
  "HLAprofiler" = "RNA",
  "seq2HLA" = "RNA",
  "Optitype-RNA" = "RNA",
  "HLA*LA" = "DNA",
  "LENS-v1.8-consensus" = "DNA and RNA",
  "Kourami" = "DNA",
  "Optitype-DNA" = "DNA",
  "Polysolver" = "DNA",
  "nf-hlamajority" = "DNA"
)

df.for.figure$datatype <- tool_types[as.character(df.for.figure$Tool)]
figure <- ggplot(df.for.figure, aes(x = Tool_ordered, y = Accuracy)) +
  geom_col(
    aes(fill = datatype),
    width = 0.7,
    color = "black",
    linewidth = 0.2
  ) +
  facet_wrap(~Gene, scales = "free_x", ncol = 1,
             labeller = as_labeller(my_gene_labels)) +
  geom_text(
    aes(label = paste0(round(Accuracy, 1), "%")),
    vjust = -0.5,
    size = 7
  ) +
  scale_x_reordered() +
  scale_y_continuous(
    limits = c(0, 120),
    breaks = seq(0, 100, 25),
    expand = c(0,0)
  ) +
  
  labs(
    y = "Accuracy (%)",
    x = "Tool"
  ) +
  
  theme_bw() +
  coord_cartesian(ylim = c(0, 115)) +
  theme(
    strip.background = element_rect(fill = "#f0f0f0"),
    strip.text = element_text(face = "bold", size = 28),
    panel.grid.major.x = element_blank(),
    axis.title = element_text(size = 28, face = "bold"),
    axis.text = element_text(size = 16),
    axis.text.x = element_text(
      angle = 45,
      hjust = 1,
      size = 16,
      colour = "black"
    ),
    axis.text.y = element_text(colour = "black"),
    panel.spacing = unit(0.8, "lines"),
    legend.position = "right",
    legend.title = element_text(size = 18, face = "bold"),
    legend.text = element_text(size = 16)
    ) +
  scale_fill_manual(
    name = "Input type",
    values = c(
      "DNA" = "#601700",
      "RNA" = "#FF4242",
      "DNA and RNA" = "#006BA6"
    )
  ) +
  guides(color = guide_legend(override.aes = list(alpha = 1, size = 5)))

figure
ggsave(plot = figure, filename = "/hlamajority-paper/results/thesis/plots/lens-hlamajority-benchmark-cell-lines-20260525.svg", width = 15, height = 20)
ggsave(plot = figure, filename = "/hlamajority-paper/results/thesis/plots/lens-hlamajority-benchmark-cell-lines-20260525.pdf", width = 15, height = 20)
ggsave(plot = figure, filename = "/hlamajority-paper/results/thesis/figures/lens-hlamajority-benchmark-cell-lines-20260525.pdf", width = 15, height = 20)

# make wide version
figure_two_rows <- ggplot(df.for.figure, aes(x = Tool_ordered, y = Accuracy)) +
  geom_col(
    aes(fill = datatype),
    width = 0.7,
    color = "black",
    linewidth = 0.2
  ) +
  facet_wrap(~Gene, scales = "free_x", nrow = 2,
             labeller = as_labeller(my_gene_labels)) +
  geom_text(
    aes(label = paste0(round(Accuracy, 1), "%")),
    vjust = -0.5,
    size = 7
  ) +
  scale_x_reordered() +
  scale_y_continuous(
    limits = c(0, 120),
    breaks = seq(0, 100, 25),
    expand = c(0,0)
  ) +
  
  labs(
    y = "Accuracy (%)",
    x = "Tool"
  ) +
  
  theme_bw() +
  coord_cartesian(ylim = c(0, 115)) +
  theme(
    strip.background = element_rect(fill = "#f0f0f0"),
    strip.text = element_text(face = "bold", size = 28),
    panel.grid.major.x = element_blank(),
    axis.title = element_text(size = 28, face = "bold"),
    axis.text = element_text(size = 16),
    axis.text.x = element_text(
      angle = 45,
      hjust = 1,
      size = 16,
      colour = "black"
    ),
    axis.text.y = element_text(colour = "black"),
    panel.spacing = unit(0.8, "lines"),
    legend.position = "right",
    legend.title = element_text(size = 18, face = "bold"),
    legend.text = element_text(size = 16)
  ) +
  scale_fill_manual(
    name = "Input type",
    values = c(
      "DNA" = "#601700",
      "RNA" = "#FF4242",
      "DNA and RNA" = "#006BA6"
    )
  ) +
  guides(color = guide_legend(override.aes = list(alpha = 1, size = 5)))

figure_two_rows
ggsave(plot = figure_two_rows, filename = "/hlamajority-paper/results/presentation/lens-hlamajority-benchmark-cell-lines-two-rows.png", width = 20, height = 10, dpi = 600)

# figure: concordance
make_concordance_matrix <- function(df_gene) {
  df <- df_gene %>%
    mutate(
      Tool1 = as.character(Tool1),
      Tool2 = as.character(Tool2),
      Tool_min = pmin(Tool1, Tool2),
      Tool_max = pmax(Tool1, Tool2)
    ) %>%
    select(Gene, Tool1 = Tool_min, Tool2 = Tool_max, Concordance) %>%
    distinct(Tool1, Tool2, .keep_all = TRUE)
  
  tools <- unique(c(df$Tool1, df$Tool2))
  
  diag_df <- data.frame(
    Gene = unique(df$Gene),
    Tool1 = tools,
    Tool2 = tools,
    Concordance = 1
  )
  
  bind_rows(df, diag_df)
}

make_concordance_matrix_for_weighted_mean <- function(df_gene) {
  df <- df_gene %>%
    mutate(
      Tool1 = as.character(Tool1),
      Tool2 = as.character(Tool2),
      Tool_min = pmin(Tool1, Tool2),
      Tool_max = pmax(Tool1, Tool2)
    ) %>%
    select(Gene, Tool1 = Tool_min, Tool2 = Tool_max, Concordance, N) %>%
    distinct(Tool1, Tool2, .keep_all = TRUE)
  return(df)
}

concordance_df <- results$concordance %>%
  mutate(pair = paste(pmin(Tool1, Tool2), pmax(Tool1, Tool2), sep = "_"))

concordance_clean <- concordance_df %>%
  filter(Tool1 != "Optitype_ad", Tool2 != "Optitype_ad") %>%
  mutate(
    Tool1 = gsub("optitype", "Optitype-DNA", Tool1),
    Tool2 = gsub("optitype", "Optitype-DNA", Tool2)
  ) %>%
  split(.$Gene) %>%
  lapply(make_concordance_matrix) %>%
  bind_rows()

tool_levels <- c(
  "kourami", "hlala", "polysolver", "Optitype-DNA",
  "hlamajority", "arcasHLA", "HLAprofiler", "seq2HLA",
  "Optitype_ar", "LENS-v1.8-consensus"
)

tool_labels <- c(
  "Kourami", "HLA*LA", "Polysolver", "Optitype-DNA",
  "nf-hlamajority", "arcasHLA", "HLAprofiler", "seq2HLA",
  "Optitype-RNA", "LENS-v1.8-consensus"
)

concordance_clean <- concordance_clean %>%
  mutate(
    Tool1 = factor(Tool1, levels = tool_levels, labels = tool_labels),
    Tool2 = factor(Tool2, levels = tool_levels, labels = tool_labels)
  ) %>%
  mutate(
    Tool1_chr = as.character(Tool1),
    Tool2_chr = as.character(Tool2)
  ) %>%
  mutate(
    Tool_min = ifelse(Tool1_chr < Tool2_chr, Tool1_chr, Tool2_chr),
    Tool_max = ifelse(Tool1_chr < Tool2_chr, Tool2_chr, Tool1_chr)
  ) %>%
  select(Gene, Tool1 = Tool_min, Tool2 = Tool_max, Concordance) %>%
  distinct(Tool1, Tool2, Gene, .keep_all = TRUE)

my_gene_labels_remove_total <- c(
  "A"     = "HLA-A",
  "B"     = "HLA-B",
  "C"     = "HLA-C"
) 

heatmap <- ggplot(concordance_clean, aes(Tool2, Tool1, fill = Concordance)) +
  geom_tile(color = "white") +
  geom_text(aes(label = round(Concordance, 2)), size = 3) +
  facet_wrap(~Gene,
             labeller = as_labeller(my_gene_labels_remove_total)
             ) +
  scale_fill_gradient2(
    low = "blue", high = "red",
    limit = c(0,1),
    name = "Concordance"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    axis.text = element_text(color = "black", size = 11),
    legend.position = "right",
    legend.title = element_text(face = "bold"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1),
    strip.background = element_rect(color = "black", fill = "grey90", linewidth = 1),
    strip.text = element_text(face = "bold", size = 16),
    panel.spacing = unit(1, "lines")
  )

heatmap

concordance_df_clean_for_weighted <- concordance_df %>%
  filter(Tool1 != "Optitype_ad", Tool2 != "Optitype_ad") %>%
  mutate(
    Tool1 = gsub("optitype", "Optitype-DNA", Tool1),
    Tool2 = gsub("optitype", "Optitype-DNA", Tool2)
  ) %>%
  split(.$Gene) %>%
  lapply(make_concordance_matrix_for_weighted_mean) %>%
  bind_rows()

concordance_df_clean_for_weighted <- concordance_df_clean_for_weighted %>%
  mutate(
    Tool1 = factor(Tool1, levels = tool_levels, labels = tool_labels),
    Tool2 = factor(Tool2, levels = tool_levels, labels = tool_labels)
  ) %>%
  mutate(
    Tool1_chr = as.character(Tool1),
    Tool2_chr = as.character(Tool2)
  ) %>%
  mutate(
    Tool_min = ifelse(Tool1_chr < Tool2_chr, Tool1_chr, Tool2_chr),
    Tool_max = ifelse(Tool1_chr < Tool2_chr, Tool2_chr, Tool1_chr)
  ) %>%
  select(Gene, Tool1 = Tool_min, Tool2 = Tool_max, Concordance, N) %>%
  distinct(Tool1, Tool2, Gene, .keep_all = TRUE)

per_tool_concordance_weighted <- concordance_df_clean_for_weighted %>%
  tidyr::pivot_longer(
    cols = c(Tool1, Tool2),
    names_to = "role",
    values_to = "Tool"
  ) %>%
  group_by(Gene, Tool) %>%
  summarise(
    Mean_Concordance = weighted.mean(Concordance, w = N, na.rm = TRUE),
    Total_Comparisons = sum(N),
    N_pairs = n(),
    .groups = "drop"
  )
tool_labels_levels <- data.frame(Tool = tool_labels, levels = tool_levels)
per_tool_concordance_weighted_levels <- left_join(per_tool_concordance_weighted, tool_labels_levels)
 
# add accuracy
accuracy_df <- results$summary %>%
  dplyr::select(Gene, Tool, Accuracy) %>%
  dplyr::mutate(
    Accuracy = Accuracy * 100,
    levels = Tool
  ) %>%
  dplyr::select(-Tool) %>% 
  filter(levels != "Optitype_ad") %>% 
  mutate(levels = gsub(pattern = "optitype", replacement = "Optitype-DNA", x = levels)) %>% 
  mutate(levels = gsub(pattern = "-LENS", x = levels,replacement = "")) %>% 
  dplyr::filter(levels != "Optitype-DNA-hlamajority")

by <- join_by(Tool == levels, Gene)

per_tool_concordance_weighted_levels <- per_tool_concordance_weighted_levels %>%
                                        dplyr::left_join(accuracy_df, by = by) %>%
                                        mutate(Mean_Concordance = 100*Mean_Concordance)
# default is pearson correlation
per_tool_concordance_weighted_levels_cor <- per_tool_concordance_weighted_levels %>% 
                                            group_by(Gene) %>% 
                                            summarise(cor = cor(Accuracy, Mean_Concordance, use = "complete.obs"))

cor_labels <- per_tool_concordance_weighted_levels_cor %>%
  mutate(
    label = paste0("cor = ", round(cor, 3))
  )
gene_labels <- per_tool_concordance_weighted_levels_cor %>%
  mutate(label = paste0("HLA-", Gene)) %>% #, "\ncor = ", round(cor, 3))) %>%
  select(Gene, label) %>%
  deframe()  

weighted_concordance_per_tool_plot <- ggplot(per_tool_concordance_weighted,
       aes(x = reorder_within(Tool, Mean_Concordance, Gene), 
           y = 100*Mean_Concordance)) +
       # aes(x = reorder(Tool, Mean_Concordance),
       #     y = Mean_Concordance)) +
         scale_x_reordered() +
  geom_col(fill = "steelblue") +
  coord_flip() +
  facet_wrap(~Gene, 
             scales = "free_y",
             labeller = as_labeller(gene_labels)
  ) +
  labs(y = "Mean Concordance (%)", x = "Tool") +
  theme_minimal() +
  theme(
    axis.text = element_text(color = "black", size = 10),
    axis.text.y = element_text(size = 11),
    axis.title = element_text(face = "bold", size = 16),
    strip.background = element_rect(fill = "grey90", color = "black"),
    strip.text = element_text(face = "bold", size = 16),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1),
  )
weighted_concordance_per_tool_plot

# plot accuracy vs concordance
top_tools <- per_tool_concordance_weighted_levels %>%
  group_by(Gene) %>%
  filter(Mean_Concordance == max(Mean_Concordance, na.rm = TRUE)) %>%
  select(Gene, Tool, Mean_Concordance)

top_tools_label <- top_tools %>%
  group_by(Gene) %>%
  summarise(
    top_tool = paste(Tool, collapse = ", "),
    top_acc = unique(Mean_Concordance),
    .groups = "drop"
  )

annotation_df <- per_tool_concordance_weighted_levels_cor %>%
  left_join(top_tools_label, by = "Gene") %>%
  mutate(
    label = paste0(
      "cor = ", round(cor, 2),
      " | Top concordance: ", top_tool,
      " (", round(top_acc, 2), "%)"
    )
  )


accuracy_vs_concordance <- ggplot(per_tool_concordance_weighted_levels, aes(x = Accuracy, y = Mean_Concordance)) +
  geom_point(size = 3, alpha = 0.8) +
  facet_wrap(~Gene, labeller = as_labeller(gene_labels)) +
  geom_smooth(method = "lm", se = FALSE, color = "black", linewidth = 0.5) +

  labs(
    y = "Mean Concordance (%)",
    x = "Accuracy (%)"
  ) +
  geom_label(
    data = annotation_df,
    aes(x = -Inf, y = Inf, label = label),
    inherit.aes = FALSE,
    hjust = -0.03,
    vjust = 1.3,
    fill = "white",
    label.size = 0.2,
    size = 3.6
  ) +
  theme_minimal() +
  theme(
    axis.text = element_text(color = "black", size = 12),
    axis.title = element_text(face = "bold", size = 16),
    strip.background = element_rect(fill = "grey90", color = "black"),
    strip.text = element_text(face = "bold", size = 16),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)
  )
accuracy_vs_concordance

# make figure: concordance matrix, weighted mean concordance, accuracy vs concordance
combine.concordance.weighted.accuracy <- ggarrange(
  heatmap, 
  weighted_concordance_per_tool_plot,
  accuracy_vs_concordance, 
  ncol = 1,
  labels = c("A", "B", "C"),
  font.label=list(color="black",size=28, face = "bold")
)
ggsave(combine.concordance.weighted.accuracy, filename = "/hlamajority-paper/results/thesis/plots/concordance-accuracy-20260526.svg", width = 15, height = 20)
ggsave(combine.concordance.weighted.accuracy, filename = "/hlamajority-paper/results/thesis/plots/concordance-accuracy-20260526.pdf", width = 15, height = 20)
ggsave(combine.concordance.weighted.accuracy, filename = "/hlamajority-paper/results/thesis/figures/concordance-accuracy-20260526.pdf", width = 15, height = 20)
lens_1.8_calls_A <- names(results$details$A$`LENS-v1.8-consensus`$metrics$gold_standard_list)
seq2hla_calls_A <- names(results$details$A$seq2HLA$metrics$gold_standard_list)
lens_1.8_calls_C <- names(results$details$C$`LENS-v1.8-consensus`$metrics$gold_standard_list)
optitype_calls_A <- names(results$details$A$Optitype_ad$metrics$gold_standard_list)
optitype_calls_C <- names(results$details$C$Optitype_ad$metrics$gold_standard_list)
outersect <- function(x, y) {
  sort(c(setdiff(x, y),
         setdiff(y, x)))
}
missing_calls_lens_a <- outersect(lens_1.8_calls_A, optitype_calls_A)
missing_calls_lens_c <- outersect(lens_1.8_calls_C, optitype_calls_C)
missing_calls_seq2hla_a <- outersect(seq2hla_calls_A, optitype_calls_A)

df_results <- results$summary %>% dplyr::mutate(Call_Rate = 100*Call_Rate)
df_results$Gene <- factor(df_results$Gene, levels = c("Overall", "A", "B", "C"))
df_results <- df_results %>%
  dplyr::mutate(
    Tool_ordered = reorder_within(Tool, Call_Rate, Gene)
  )
df_results$dataset <- "NCI-60 Cell Lines"
# results RDS object 1000 Genomes
results_hlamajority <- readRDS("../../data/processed/1000-genomes/majority/1000-genomes-full-results-hlamajority-majority-vote.Rds")
df_results_hlamajority <- results_hlamajority$summary %>% dplyr::mutate(Call_Rate = 100*Call_Rate)
df_results_hlamajority$Gene <- factor(df_results_hlamajority$Gene, levels = c("Overall", "A", "B", "C"))
df_results_hlamajority <- df_results_hlamajority %>%
  dplyr::mutate(
    Tool_ordered = reorder_within(Tool, Call_Rate, Gene)
  )
df_results_hlamajority$dataset <- "1000 Genomes"

df_results_combined <- rbind(df_results, df_results_hlamajority)

df_results_combined_clean <- df_results_combined %>% 
  dplyr::filter(Tool != "Optitype-DNA-LENS") %>% 
  mutate(Tool = gsub("Optitype-DNA-hlamajority", "Optitype-DNA", Tool)) %>% 
  mutate(
  Tool = gsub("hlala", "HLA*LA", Tool),
  Tool = gsub("kourami", "Kourami", Tool),
  Tool = gsub("^hlamajority", "nf-hlamajority", Tool),
  Tool = gsub("optitype", "Optitype-DNA", Tool),
  Tool = gsub("polysolver", "Polysolver", Tool)
) 

df_results_combined_clean_ordered <- df_results_combined_clean %>%
  mutate(Tool_ordered2 = reorder_within(Tool, Call_Rate, dataset))
df_results_combined_clean_ordered <- df_results_combined_clean_ordered %>% dplyr::mutate(Gene = paste("HLA-", sep = "", Gene))

df_results_combined_clean_ordered$datatype <- tool_types[as.character(df_results_combined_clean_ordered$Tool)]
p_call_combined <- ggplot(df_results_combined_clean_ordered, aes(x = Tool_ordered2, y = Call_Rate)) +
  geom_col(
    aes(fill = datatype),
    width = 0.7,
    color = "black",
    linewidth = 0.2
  ) +
  scale_fill_manual(
    name = "Input type",
    values = c(
      "DNA" = "#601700",
      "RNA" = "#FF4242",
      "DNA and RNA" = "#006BA6"
    )
  ) +
  facet_grid(Gene ~ dataset, scales = "free_x", space = "free_x") +
  geom_text(
    aes(label = paste0(round(Call_Rate, 1), "%")),
    vjust = -0.5,
    size = 3.5
  ) +
  #scale_x_reordered(labels = label_vector_call_rate) +
  scale_x_reordered() +
  
  scale_y_continuous(
    limits = c(0, 120),
    breaks = seq(0, 100, 25),
    expand = c(0, 0)
  ) +
  
  labs(
    y = "Call rate (%)",
    x = "Tool"
  ) +
  
  theme_bw() +
  coord_cartesian(ylim = c(0, 115)) +
  
  theme(
    strip.background = element_rect(fill = "#f0f0f0"),
    strip.text = element_text(face = "bold", size = 14),
    panel.grid.major.x = element_blank(),
    axis.title = element_text(size = 16, face = "bold"),
    axis.text = element_text(size = 12, colour = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.spacing = unit(0.8, "lines"),
    legend.title = element_text(face = "bold")
  ) 

p_call_combined

ggsave(p_call_combined, filename = "/hlamajority-paper/results/thesis/plots/call-rates-20260526.svg", width = 15, height = 10)
ggsave(p_call_combined, filename = "/hlamajority-paper/results/thesis/plots/call-rates-20260526.pdf", width = 15, height = 10)
ggsave(p_call_combined, filename = "/hlamajority-paper/results/thesis/figures/call-rates-20260526.pdf", width = 15, height = 10)

# plot false positives false negatives
stats <- read.csv("../../scripts/thesis/nf-neoantigen/results-benchmark-remove-duplicate-q61h-20260603/combined/combined_stats_out.csv")
summaries <- read.csv("../../scripts/thesis/nf-neoantigen/results-benchmark-remove-duplicate-q61h-20260603/combined/summaries_combined_out.csv")
summaries_binder_loss <- summaries %>% dplyr::filter(binder_loss == TRUE)

plot_df <- stats %>%
  group_by(Tool) %>%
  summarise(
    binder_gain = sum(n_binder_gain),
    binder_loss = sum(n_binder_loss),
    strong_binder_gain = sum(n_strong_binder_gain),
    strong_binder_loss = sum(n_strong_binder_loss)
  ) %>%
  tidyr::pivot_longer(
    cols = -Tool,
    names_to = "event",
    values_to = "count"
  )

ggplot(plot_df, aes(x = Tool, y = count, fill = event)) +
  geom_col(position = "dodge")

plot_df %>% dplyr::filter(event %in% c("binder_loss", "binder_gain")) %>% group_by(Tool) %>% summarise(n_error = sum(count)) %>% 
  ggplot(., aes(x = Tool, y = n_error)) +
  geom_col(position = "dodge") +
  ylab("Number of errors weak binders")

head(plot_df)

plot_df_per_gene <- stats %>%
  group_by(Tool, HLA_gene) %>%
  summarise(
    binder_gain = sum(n_binder_gain),
    binder_loss = sum(n_binder_loss),
    strong_binder_gain = sum(n_strong_binder_gain),
    strong_binder_loss = sum(n_strong_binder_loss)
  ) %>%
  tidyr::pivot_longer(
    cols = -c(Tool, HLA_gene),
    names_to = "event",
    values_to = "count"
  ) %>% 
  mutate(Strong_weak = ifelse(grepl("strong", event), "Strong", "Weak"))

plot_df_per_gene$event <- factor(
  plot_df_per_gene$event,
  levels = c("binder_loss", "binder_gain", "strong_binder_loss", "strong_binder_gain"),
  labels = c("Binder loss", "Binder gain", "Strong binder loss", "Strong binder gain")
)

plot_df_per_gene$HLA_gene <- factor(
  plot_df_per_gene$HLA_gene,
  levels = c("A", "B", "C"),
  labels = c("HLA-A", "HLA-B", "HLA-C")
)

plot_df_per_gene$Tool <- factor(
  plot_df_per_gene$Tool,
  levels = c("LENS-v1.8-consensus", "hlamajority"),
  labels = c("LENS-v1.8-consensus", "nf-hlamajority")
)

plot_df_per_gene_strong <- plot_df_per_gene %>% dplyr::filter(event %in% c("Strong binder gain", "Strong binder loss"))
plot_df_per_gene_weak <- plot_df_per_gene %>% dplyr::filter(event %in% c("Binder gain", "Binder loss"))

# palette_mistake_types_neoant <- c(
#   "Binder gain" = "#016FB9",
#   "Binder loss" = "#22AED1",
#   "Strong binder gain" = "#6D8EA0",
#   "Strong binder loss" = "#AFA98D"
# )

palette_mistake_types_neoant <- c(
  "Binder gain" = "#016FB9",
  "Binder loss" = "#758E4F",
  "Strong binder gain" = "#016FB9",
  "Strong binder loss" = "#758E4F"
)
number_of_errors_weak_per_gene <- ggplot(
  plot_df_per_gene_weak,
  aes(x = event, y = count, fill = event)
) +
  geom_col( 
    width = 0.7,
    color = "black",
    linewidth = 0.2
  ) +
  facet_grid(
    HLA_gene ~ Tool,
    scales = "fixed",
    labeller = labeller(Gene = my_gene_labels)
  ) +
  scale_y_continuous(
    limits = c(0, 50),
    breaks = seq(0, 50, by = 10),
    expand = c(0, 0)  
  ) +
  labs( 
    # x = "Error type",
    x = "",
    y = "Weak binder\nnumber of errors",
    fill = "Error type"
  ) +
  theme_bw() +
  theme(
    strip.background = element_rect(fill = "#f0f0f0"),
    strip.text = element_text(face = "bold", size = 18),
    panel.grid.major.x = element_blank(),
    axis.text = element_text(colour = "black", size = 14),
    axis.title = element_text(size = 18),
    #legend.title = element_text(size =18),
    #legend.text = element_text(size = 16),
    axis.text.x = element_text(size = 12),
    panel.spacing.y = unit(1, "lines"),
    legend.position = "none"
  ) +
  scale_fill_manual(values = palette_mistake_types_neoant)
number_of_errors_weak_per_gene
number_of_errors_strong_per_gene <- ggplot(
  plot_df_per_gene_strong,
  aes(x = event, y = count, fill = event)
) +
  geom_col( 
    width = 0.7,
    color = "black",
    linewidth = 0.2
  ) +
  facet_grid(
    HLA_gene ~ Tool,
    scales = "fixed",
    labeller = labeller(Gene = my_gene_labels)
  ) +
  scale_y_continuous(
    limits = c(0, 18),
    breaks = seq(0, 15, by = 5),
    expand = c(0, 0)  
  ) +
  labs( 
    # x = "Error type",
    x = "",
    y = "Strong binder\nnumber of errors",
    fill = "Error type"
  ) +
  theme_bw() +
  theme(
    strip.background = element_rect(fill = "#f0f0f0"),
    strip.text = element_text(face = "bold", size = 18),
    panel.grid.major.x = element_blank(),
    axis.text = element_text(colour = "black", size = 14),
    axis.title = element_text(size = 18),
    #legend.title = element_text(size =18),
    #legend.text = element_text(size = 16),
    axis.text.x = element_text(size = 12),
    panel.spacing.y = unit(1, "lines"),
    legend.position = "none"
  ) +
  scale_fill_manual(values = palette_mistake_types_neoant)
number_of_errors_strong_per_gene
plot_df_per_gene_weak_summary <- plot_df_per_gene_weak %>% 
                                 dplyr::filter(Strong_weak == "Weak") %>% 
                                 group_by(Tool) %>% 
                                 summarise(n_error = sum(count))

plot_df_per_gene_weak_summary

palette_lens_hlamajority <- c(
  "nf-hlamajority" = "#DB5461",
  "LENS-v1.8-consensus" = "#08415C"
)

plot_df_per_gene_weak_summary$Tool <- factor(plot_df_per_gene_weak_summary$Tool,
                                   levels = c("LENS-v1.8-consensus", "nf-hlamajority")
                                   #labels = c("Dropout", "Allele Gain", "Partial Mismatch", "Complete Mismatch")
)

n_errors_weak <- ggplot(
  plot_df_per_gene_weak_summary,
  aes(x = Tool, y = n_error, fill = Tool)
) +
  geom_col( 
    width = 0.7,
    color = "black",
    linewidth = 0.2
  ) +
  scale_y_continuous(
    limits = c(0, 70),
    #breaks = seq(0, 15, by = 5),
    expand = c(0, 0)  
  ) +
  theme_bw() +
  theme(
    panel.grid.major.x = element_blank(),
    axis.text = element_text(colour = "black", size = 14),
    axis.title.x = element_blank(),
    axis.title.y = element_text(size = 18),
    legend.position = "none",
    plot.title = element_text(color="black", size=28, face="bold.italic")
  ) +
  labs(
    y = "Weak binder\nnumber of errors"
  ) +
  scale_fill_manual(values = palette_lens_hlamajority) +
  ggtitle("Neoantigen prediction errors")
n_errors_weak  
plot_df_per_gene_strong_summary <- plot_df_per_gene_strong %>% 
  dplyr::filter(Strong_weak == "Strong") %>% 
  group_by(Tool) %>% 
  summarise(n_error = sum(count))

n_errors_strong <- ggplot(
  plot_df_per_gene_strong_summary,
  aes(x = Tool, y = n_error, fill = Tool)
) +
  geom_col( 
    width = 0.7,
    color = "black",
    linewidth = 0.2
  ) +
  scale_y_continuous(
    # limits = c(0, 24),
    limits = c(0,70),
    #breaks = seq(0, 15, by = 5),
    expand = c(0, 0)  
  ) +
  theme_bw() +
  theme(
    panel.grid.major.x = element_blank(),
    axis.text = element_text(colour = "black", size = 14),
    axis.title.x = element_blank(),
    axis.title.y = element_text(size = 18),
    legend.position = "none",
    plot.title = element_text(color="black", size=28, face="bold.italic")
  ) +
  labs(
    y = "Strong binder\nnumber of errors"
  ) +
  scale_fill_manual(values = palette_lens_hlamajority) +
  ggtitle("")
n_errors_strong
summarise_gene_tool <- function(results, gene, tool) {
  
  x <- results$details[[gene]][[tool]]$error_types$Type
  
  tab <- table(x)
  
  data.frame(
    Gene  = gene,
    Tool  = tool,
    Type  = names(tab),
    Count = as.integer(tab),
    row.names = NULL
  )
}
tools <-  c("hlamajority", "LENS-v1.8-consensus")
genes <- c("A", "B", "C")
final_df <- do.call(
  rbind,
  lapply(genes, function(g) {
    do.call(
      rbind,
      lapply(tools, function(t) {
        summarise_gene_tool(results, g, t)
      })
    )
  })
)   

final_df_mismatches <- final_df |>
  dplyr::filter(Type != "Correct") |>
  group_by(Gene, Tool) |>
  mutate(
    Percent = Count / sum(Count) * 100
  ) |>
  ungroup()

final_df_mismatches$Type <- factor(final_df_mismatches$Type,
                                   levels = c("Dropout (Hetero -> Homo)", "Hallucination (Homo -> Hetero)", "Partial Mismatch", "Complete Mismatch"),
                                   labels = c("Dropout", "Allele Gain", "Partial Mismatch", "Complete Mismatch")
)

final_df_mismatches$Tool <- factor(final_df_mismatches$Tool,
                                   levels = c("LENS-v1.8-consensus", "hlamajority"),
                                   labels = c("LENS-v1.8-consensus", "nf-hlamajority")
)

palette_mistake_types <- c(
  Correct = "#016FB9",
  Dropout = "#22AED1",
  "Allele Gain" = "#6D8EA0",
  "Partial Mismatch" = "#AFA98D",
  "Complete Mismatch" = "#182825"
)

p_types_percent <- ggplot(
  final_df_mismatches,
  aes(x = Type, y = Percent, fill = Type)
) +
  geom_col( 
    width = 0.7,
    color = "black",
    linewidth = 0.2
  ) +
  facet_grid(
    Gene ~ Tool,
    scales = "fixed",
    labeller = labeller(Gene = my_gene_labels)
  ) +
  scale_y_continuous(
    expand = c(0, 0)
  ) +
  labs( 
    x = "Outcome type",
    y = "Percent of genotyping errors",
    fill = "Type"
  ) +
  theme_bw() +
  theme(
    strip.background = element_rect(fill = "#f0f0f0"),
    strip.text = element_text(face = "bold", size = 18),
    panel.grid.major.x = element_blank(),
    # axis.text.x = element_text(
    #   angle = 45,
    #   hjust = 1,
    #   colour = "black"
    # ),
    axis.text.x = element_blank(),
    axis.text.y = element_text(colour = "black", size = 14),
    axis.title = element_text(size = 18),
    legend.position = "bottom",
    legend.title = element_text(size =18),
    legend.text = element_text(size = 16)
  ) +
  coord_cartesian(ylim = c(0, 100)) +
  scale_fill_manual(values = palette_mistake_types)

p_types_percent

p_types_counts <- ggplot(
  final_df_mismatches,
  aes(x = Type, y = Count, fill = Type)
) +
  geom_col( 
    width = 0.7,
    color = "black",
    linewidth = 0.2
  ) +
  facet_grid(
    Gene ~ Tool,
    scales = "fixed",
    labeller = labeller(Gene = my_gene_labels)
  ) +
  scale_y_continuous(
    limits = c(0, 10),
    breaks = seq(0, 10, by = 2),
    expand = c(0, 0)  
  ) +
  labs( 
    x = "Error type",
    y = "Number of genotyping errors",
    fill = "Type"
  ) +
  theme_bw() +
  theme(
    strip.background = element_rect(fill = "#f0f0f0"),
    strip.text = element_text(face = "bold", size = 18),
    panel.grid.major.x = element_blank(),
    # axis.text.x = element_text(
    #   angle = 45,
    #   hjust = 1,
    #   colour = "black"
    # ),
    axis.text.x = element_blank(),
    axis.text.y = element_text(colour = "black", size = 14),
    axis.title = element_text(size = 18),
    legend.position = "bottom",
    legend.title = element_text(size =18),
    legend.text = element_text(size = 16),
    panel.spacing.y = unit(1.2, "lines"),
    plot.title = element_text(color="black", size=28, face="bold.italic")
  ) +
  # coord_cartesian(ylim = c(0, 10)) +
  scale_fill_manual(values = palette_mistake_types) +
  ggtitle("HLA genotyping errors")

p_types_counts

# find out how many samples are affected by errors
summaries_binder_gain_lens <- summaries %>% dplyr::filter(Tool == "LENS-v1.8-consensus" & binder_gain == TRUE)
samples_binder_gain_lens <- length(unique(summaries_binder_gain_lens$Sample))
summaries_binder_loss_lens <- summaries %>% dplyr::filter(Tool == "LENS-v1.8-consensus" & binder_loss == TRUE)
samples_binder_loss_lens <- length(unique(summaries_binder_loss_lens$Sample))
summaries_binder_gain_hlamajority <- summaries %>% dplyr::filter(Tool == "hlamajority" & binder_gain == TRUE)
samples_binder_gain_hlamajority <- length(unique(summaries_binder_gain_hlamajority$Sample))
summaries_binder_loss_hlamajority <- summaries %>% dplyr::filter(Tool == "hlamajority" & binder_loss == TRUE)
samples_binder_loss_hlamajority <- length(unique(summaries_binder_loss_hlamajority$Sample))

summarise_sample_level <- summaries %>% group_by(Tool) %>%
  summarise(
    binder_loss =
      n_distinct(Sample[binder_loss]),
    
    binder_gain =
      n_distinct(Sample[binder_gain]),
    
    strong_binder_loss = 
      n_distinct(Sample[strong_binder_loss]),
    
    strong_binder_gain = 
      n_distinct(Sample[strong_binder_gain])
  )
summarise_sample_level_long <- summarise_sample_level %>% 
pivot_longer(
  cols = -Tool,
  names_to = "metric",
  values_to = "n_samples"
)

p_samples <- ggplot(
  summarise_sample_level_long,
  aes(x = metric, y = n_samples, fill = metric)
) +
  geom_col( 
    width = 0.7,
    color = "black",
    linewidth = 0.2
  ) +
  facet_grid(
    metric ~ Tool,
    scales = "fixed"#,
    #labeller = labeller(Gene = my_gene_labels)
  ) +
  scale_y_continuous(
    limits = c(0, 10),
    breaks = seq(0, 10, by = 2),
    expand = c(0, 0)  
  ) +
  labs( 
    x = "Error type",
    y = "Number of samples affected"#,
    #fill = "Type"
  ) +
  theme_bw() +
  theme(
    strip.background = element_rect(fill = "#f0f0f0"),
    strip.text = element_text(face = "bold", size = 18),
    panel.grid.major.x = element_blank(),
    # axis.text.x = element_text(
    #   angle = 45,
    #   hjust = 1,
    #   colour = "black"
    # ),
    axis.text.x = element_blank(),
    axis.text.y = element_text(colour = "black", size = 14),
    axis.title = element_text(size = 18),
    legend.position = "bottom",
    legend.title = element_text(size =18),
    legend.text = element_text(size = 16),
    panel.spacing.y = unit(1.2, "lines")#,
    #plot.title = element_text(color="black", size=28, face="bold.italic")
  ) #+
  # coord_cartesian(ylim = c(0, 10)) +
  #scale_fill_manual(values = palette_mistake_types) +
  #ggtitle("Number of samples affected")

plot_df <- summarise_sample_level %>%
  pivot_longer(
    cols = -Tool,
    names_to = "metric",
    values_to = "n_samples"
  ) %>%
  mutate(
    metric = recode(
      metric,
      samples_with_binder_loss = "Binder loss",
      samples_with_binder_gain = "Binder gain",
      samples_with_strong_binder_loss = "Strong binder loss",
      samples_with_strong_binder_gain = "Strong binder gain"
    )
  )
plot_df$Tool <- factor(
  plot_df$Tool,
  levels = c("LENS-v1.8-consensus", "hlamajority"),
  labels = c("LENS-v1.8-consensus", "nf-hlamajority")
)
plot_df$metric <- factor(
  plot_df$metric,
  levels = c("binder_loss", "binder_gain", "strong_binder_loss", "strong_binder_gain"),
  labels = c("Binder loss", "Binder gain", "Strong binder loss", "Strong binder gain")
)
plot_number_of_samples <- ggplot(
  plot_df,
  aes(x = Tool, y = n_samples, fill = Tool)
) +
  geom_col(
    width = 0.7,
    color = "black",
    linewidth = 0.2
  ) +
  facet_wrap(~ metric, scales = "fixed") +
  theme_bw() +
  theme(
    panel.grid.major.x = element_blank(),
    axis.text = element_text(size = 16, colour = "black"),
    axis.title.y = element_text(size = 18, colour = "black"),
    legend.position = "none",
    strip.text = element_text(face = "bold", size = 18)
  ) +
  labs(
    x = NULL,
    y = "Number of samples with at least\none instance of error type"
  ) +
  scale_fill_manual(values = palette_lens_hlamajority) +
  scale_y_continuous(
    limits = c(0, 11),
    breaks = seq(0, 10, by = 2),
    expand = c(0, 0)  
  ) 
# combine.neoantigen.prediction.errors <- ggarrange(
#   ggarrange(n_errors_weak, n_errors_strong, 
#             ncol = 2, 
#             labels = c("A", "B"),
#             font.label=list(color="black",size=26, face = "bold")
#             ),
#   ggarrange(number_of_errors_weak_per_gene, 
#             number_of_errors_strong_per_gene, 
#             ncol = 2,
#             labels = c("C", "D"),
#             font.label=list(color="black",size=26, face = "bold")
#             ),
#   plot_number_of_samples,
#   p_types_counts,
#   nrow = 4,
#   heights = c(1, 2, 2, 2),
#   labels = c("", "", "E", "F"),
#   font.label=list(color="black",size=26, face = "bold")
# )

combine.neoantigen.prediction.errors <- ggarrange(
  p_types_counts,
  ggarrange(n_errors_weak, n_errors_strong, 
            ncol = 2, 
            labels = c("B", "C"),
            font.label=list(color="black",size=26, face = "bold")
  ),
  ggarrange(number_of_errors_weak_per_gene, 
            number_of_errors_strong_per_gene, 
            ncol = 2,
            labels = c("D", "E"),
            font.label=list(color="black",size=26, face = "bold")
  ),
  plot_number_of_samples,
  nrow = 4,
  heights = c(2, 1, 2, 2),
  labels = c("A", "", "", "F"),
  font.label=list(color="black",size=26, face = "bold")
)

# ggsave(plot = combine.neoantigen.prediction.errors, filename = "/hlamajority-paper/results/thesis/test/test.pdf", width = 16, height = 20)
# ggsave(plot = combine.neoantigen.prediction.errors, filename = "/hlamajority-paper/results/thesis/plots/neoantigen-prediction-errors-20260528.svg", width = 16, height = 20)
# ggsave(plot = combine.neoantigen.prediction.errors, filename = "/hlamajority-paper/results/thesis/plots/neoantigen-prediction-errors-20260528.pdf", width = 16, height = 20)
# ggsave(plot = combine.neoantigen.prediction.errors, filename = "/hlamajority-paper/results/thesis/figures/neoantigen-prediction-errors-20260528.pdf", width = 16, height = 20)
ggsave(plot = combine.neoantigen.prediction.errors, filename = "/hlamajority-paper/results/thesis/plots/neoantigen-prediction-errors-update-20260602.svg", width = 16, height = 20)
ggsave(plot = combine.neoantigen.prediction.errors, filename = "/hlamajority-paper/results/thesis/plots/neoantigen-prediction-errors-20260602.pdf", width = 16, height = 20)
ggsave(plot = combine.neoantigen.prediction.errors, filename = "/hlamajority-paper/results/thesis/figures/neoantigen-prediction-errors-20260602.pdf", width = 16, height = 20)

